# Generated by Django 4.2.2 on 2023-06-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_code', models.CharField(max_length=10)),
                ('bp_name', models.CharField(max_length=100)),
                ('customer_site', models.CharField(max_length=100)),
                ('district', models.CharField(choices=[('Bugesera', 'Bugesera'), ('Burera', 'Burera'), ('Gakenke', 'Gakenke'), ('Gasabo', 'Gasabo'), ('Gatsibo', 'Gatsibo'), ('Gicumbi', 'Gicumbi'), ('Gisagara', 'Gisagara'), ('Huye', 'Huye'), ('Kamonyi', 'Kamonyi'), ('Karongi', 'Karongi'), ('Kayonza', 'Kayonza'), ('Kicukiro', 'Kicukiro'), ('Kirehe', 'Kirehe'), ('Muhanga', 'Muhanga'), ('Musanze', 'Musanze'), ('Ngoma', 'Ngoma'), ('Ngororero', 'Ngororero'), ('Nyabihu', 'Nyabihu'), ('Nyagatare', 'Nyagatare'), ('Nyamagabe', 'Nyamagabe'), ('Nyamasheke', 'Nyamasheke'), ('Nyanza', 'Nyanza'), ('Nyarugenge', 'Nyarugenge'), ('Nyaruguru', 'Nyaruguru'), ('Rubavu', 'Rubavu'), ('Ruhango', 'Ruhango'), ('Rulindo', 'Rulindo'), ('Rusizi', 'Rusizi'), ('Rutsiro', 'Rutsiro'), ('Rwamagana', 'Rwamagana'), ('Kenya', 'Kenya'), ('Tanzania', 'Tanzania')], max_length=100)),
                ('profile', models.CharField(choices=[('Government', 'Government'), ('Private', 'Private')], max_length=20)),
                ('sector', models.CharField(choices=[('CENTRAL GOV', 'CENTRAL GOV'), ('TECH', 'TECH')], max_length=20)),
                ('customer_category', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('bw', models.IntegerField()),
                ('item_description', models.CharField(max_length=100)),
                ('kms_dfl_only', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_sales', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('billing_cycle', models.CharField(max_length=20)),
                ('end_date', models.DateField()),
                ('agreement_days', models.IntegerField(editable=False)),
                ('contract_status', models.CharField(editable=False, max_length=100)),
                ('account_manager', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('cp_email', models.EmailField(max_length=254)),
                ('cp_phone', models.CharField(max_length=15)),
                ('comment', models.TextField()),
            ],
        ),
    ]
