# Generated by Django 4.2.2 on 2023-06-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='bw',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='kms_dfl_only',
            field=models.IntegerField(null=True),
        ),
    ]
