# Generated by Django 4.2.2 on 2023-06-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_report_bw_alter_report_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='kms_dfl_only',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
