# Generated by Django 4.2.2 on 2023-06-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_report_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='bw',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
