# Generated by Django 4.2.2 on 2023-06-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_report_bw'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sales_month',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='profile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='sector',
            field=models.CharField(max_length=20),
        ),
    ]
