# Generated by Django 4.2.2 on 2023-06-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_report_sales_month_alter_report_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='cp_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
