# Generated by Django 4.2.2 on 2023-07-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_report_comment_alter_report_cp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=20),
        ),
    ]
