# Generated by Django 4.2.2 on 2023-07-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_report_agreement_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='agreement_days',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='contract_status',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_sales',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True),
        ),
    ]
