# Generated by Django 4.2.3 on 2023-09-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_report_agreement_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='total_targets',
            field=models.IntegerField(),
        ),
    ]
